//*****************************************************************************
//denseClear.comp**************************************************************
//*****************************************************************************

#version 430

//Needs a manually added include file which defines the clearVoxels function
//and provides appropriate uniforms

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

void main()
{
	clearVoxels(ivec3(gl_GlobalInvocationID));
}

